"""Configuración central del proyecto."""
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"
MODELS_DIR = PROJECT_ROOT / "models"
REPORTS_DIR = PROJECT_ROOT / "reports"

EXCEL_FILENAME = "BBDD ONSV - SINIESTROS FATALES 2021-2025 (preliminar).xlsx"
EXCEL_PATH = DATA_DIR / EXCEL_FILENAME
SHEET_NAME = "SINIESTROS"
BEST_MODEL_PATH = MODELS_DIR / "best_model.pkl"
MODEL_METADATA_PATH = MODELS_DIR / "model_metadata.pkl"

RANDOM_STATE = 42
TEST_SIZE = 0.20
TARGET_COLUMN = "NIVEL_RIESGO"
FATALITIES_COLUMN = "CANTIDAD DE FALLECIDOS"

PREFERRED_FEATURES = [
    "FECHA SINIESTRO", "HORA SINIESTRO", "CLASE SINIESTRO", "DEPARTAMENTO",
    "PROVINCIA", "DISTRITO", "ZONA", "TIPO DE VÍA", "RED VIAL",
    "CONDICIÓN CLIMÁTICA", "ZONIFICACIÓN", "CARACTERÍSTICAS DE VÍA",
    "PERFIL LONGITUDINAL VÍA", "SUPERFICIE DE CALZADA", "CAUSA FACTOR PRINCIPAL",
    "CAUSA ESPECÍFICA", "CANTIDAD DE LESIONADOS", "CANTIDAD DE VEHICULOS DAÑADOS",
]

EXCLUDED_COLUMNS = {
    "CÓDIGO SINIESTRO", "CODIGO SINIESTRO", FATALITIES_COLUMN, TARGET_COLUMN,
    "LATITUD", "LONGITUD", "COORDENADA X", "COORDENADA Y", "UBIGEO",
}
