"""Configuración central del proyecto."""
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"
MODELS_DIR = PROJECT_ROOT / "models"
REPORTS_DIR = PROJECT_ROOT / "reports"

EXCEL_FILENAME = "BBDD ONSV - SINIESTROS FATALES 2021-2025 (preliminar).xlsx"
EXCEL_PATH = DATA_DIR / EXCEL_FILENAME
SHEET_NAME = "SINIESTROS"
BEST_MODEL_PATH = MODELS_DIR / "best_model.pkl"
MODEL_METADATA_PATH = MODELS_DIR / "model_metadata.pkl"

RANDOM_STATE = 42
TEST_SIZE = 0.20
TARGET_COLUMN = "NIVEL_RIESGO"
FATALITIES_COLUMN = "CANTIDAD DE FALLECIDOS"

PREFERRED_FEATURES = [
    "CLASE SINIESTRO",
    "CANTIDAD DE LESIONADOS",
    "CANTIDAD DE VEHICULOS DAÑADOS",
    "DEPARTAMENTO",
    "PROVINCIA",
    "DISTRITO",
    "ZONA",
    "TIPO DE VÍA",
    "RED VIAL",
    "COD CARRETERA",
    "CONDICIÓN CLIMÁTICA",
    "ZONIFICACIÓN",
    "CARACTERÍSTICAS DE VÍA",
    "PERFIL LONGITUDINAL VÍA",
    "SUPERFICIE DE CALZADA",
    "¿EXISTE SEÑAL VERTICAL?",
    "CLASIFICACIÓN DE LA SEÑAL VERTICAL Nº 1",
    "CLASIFICACIÓN DE LA SEÑAL VERTICAL Nº 2",
    "¿EXISTE SEÑAL HORIZONTAL?",
    "CAUSA FACTOR PRINCIPAL",
    "CAUSA ESPECÍFICA",
]

EXCLUDED_COLUMNS = {
    "CÓDIGO SINIESTRO", "CODIGO SINIESTRO", "FECHA SINIESTRO", "HORA SINIESTRO",
    FATALITIES_COLUMN, TARGET_COLUMN, "LATITUD", "LONGITUD", "COORDENADAS LATITUD",
    "COORDENADAS  LONGITUD", "COORDENADAS LONGITUD", "COORDENADA X", "COORDENADA Y", "UBIGEO",
}
